### ISSUE TITLE
Expose vector-tile-pb.js

### ISSUE THREAD

**Issue by GretaCB** [mapbox/vt-pbf#4]
Id love to explicitly use the functions inside `vector-tile-pb.js` to write tiles. Currently, this file is not exposed, and I'd like to avoid `require('../../node_modules/vt-pbf/vector-tile-pb.js')`. 

Any reason why this file is only internal? Thank ya!

**Comment by anandthakker** [comment]
@GretaCB Ah, interesting.  I _think_ you should be able to just do `require('vt-pbf/vector-tile-pb')` to get that one -- does that work for you?  I'm also cool w/ exporting it off the main module if this doesn't work or even if that's just preferable

Btw, I'm fine maintaining this repo here, but also be happy to transfer it over to Mapbox if it's more convenient for yall, since I noticed that gl-js (and now presumably something you're working on) are using it.

**Comment by GretaCB** [comment]
> does that work for you?

ah, indeed it does 👍  thank you!

As far as maintaining, do you have a preference? We're down either way.

**Comment by anandthakker** [comment]
> As far as maintaining, do you have a preference? We're down either way.

No real personal preference, but all else being equal, it seems like it would be easier/faster for you all to iterate if you've got the repo.  I'll transfer

**Comment by GretaCB** [comment]
👍
